version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./dockers/dev/dockerfile
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - .:/mnt/workspace
      - ./data/events.sqlite:/mnt/workspace/data/events.sqlite
    environment:
      DEBUG: "True"
